import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { Header } from "./ui/header";
import { Footer } from "./ui/footer";


import "./globals.css";

const notoSans = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={notoSans.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}

